Repository kuzzleio/sdk-php, pull requests merged in 2019-02, with the labels that each got.

#104 Add docker-compose file for dev
  docker/docker-compose.yml
Labels: changelog:enhancements

#103 Fix document create
  docker/docker-compose.yml
  src/Collection.php
  src/Document.php
  src/Kuzzle.php
  tests/DataCollectionTest.php
Labels: changelog:bug-fixes

#106 Release 3.0.5
  composer.json
  docker/docker-compose.yml
  src/Collection.php
  src/Document.php
  src/Kuzzle.php
  tests/DataCollectionTest.php
Labels: release

#105 Fix createFirstAdmin endpoint
  src/config/routes.json
Labels: 3.x, changelog:enhancements
